### ISSUE TITLE
Einstein-Rosen Bridge

### ISSUE THREAD

**Issue by caecos** [soulbridge/BBModules#3]
I really miss this module...too bad you drop it...is it possible to have the sources to build only this module!?

**Comment by robertocolabene** [comment]
Hi, I'm really sorry for the late.
I discontinued this module because after Rack updates it was completely broken. Also when I released it I didn't like how it worked, just too broken for me...
Just think that I wanted to sell that module but the result was not sellable at all.
I could think some day to remake a new version of it.
