### ISSUE TITLE
complex oscillator manual

### ISSUE THREAD

**Issue by joopvdl** [soulbridge/BBModules#4]
I find it hard to understand complex oscillator.
Is there a video or another way that explains how to use it?

**Comment by robertocolabene** [comment]
I'm really sorry for the late. There isn't a video that shows all the applications of that module.
Just let me know your doubts.
There are some things i wanna remind you:
|s|- it's the output that sum the 5 waveforms (sin,tri,saw,sqr,spl)
|c|- it's equal to |s| but the fine knob has no control on the oscillator (in order to create detuning effect between |s| and |c|)
|≈|- it's the output that sum the 5 waveforms (spl2,spl3,spl4,spl5,spl6)
|o|- it's a special output that use a carrier chosen with ã| knob and 4 modulation waves controlled by the switch near there and ḅ| knob,
ö| it's for the amount and ŧ| to change the phase

**Comment by robertocolabene** [comment]
on the top there are 4 inputs to modulate selected, by the context menu, things.
https://github.com/soulbridge/BBModules/blob/master/old/README.md
look at this

**Comment by joopvdl** [comment]
Thank you. It's a wonderful oscillator, but it is heavy on the resources. I
found out how it works, sort of. Will you update to 1.0?
Best, Joop

**Comment by robertocolabene** [comment]
Yes, the complex oscillator has a large amount of instructions in it. I don't know if I can make it lighter but if this could be a problem in the future a I will make a new lighter version.
Yes all my modules will be always update to the new versions of Rack since rack will be free for the delevopers.

**Comment by joopvdl** [comment]
Anyway, good to hear from you.
I believe having a manual would help getting more people to use the oscillator. If you feel like creating one, I could help if you need that.

**Comment by robertocolabene** [comment]
I could make a graphic manual for the |o| output that is the only characteristic part, for the rest it's, more or less, a normal oscillator with some unusual waves in it.
I'm not a fan of detailed manuals also because it's fun to use a scope to understand how things works.

**Comment by joopvdl** [comment]
I think that's an excellent idea. I love to fool around with modules, but
sometimes it's nice to know all the details :)

Op ma 29 apr. 2019 om 15:08 schreef Roberto Colabene <
notifications@github.com>:

**Comment by robertocolabene** [comment]
take a look here 
https://github.com/soulbridge/BBModules/blob/master/QSG/complexoscillator/readme.md
i think that's all, what do u think?

**Comment by joopvdl** [comment]
That is nice. I like it.


Op di 30 apr. 2019 om 00:23 schreef Roberto Colabene <
notifications@github.com>:

**Comment by robertocolabene** [comment]
Well, thank you and let me know if there are other things I can do to give you all a better experience. 👍
