### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by PrinzNika** [soulbridge/BBModules#7]
Hi there, I really like your modules. Bought them some time ago and especially Oknotok is so cool. Are you planning on picking up your coding? Would be really interested what youve got in mind for Solar. 
:)
-Nika

**Comment by robertocolabene** [comment]
hi, thank you for bought them. Since I started programming my modules I'm getting busier and busier, I will update my modules when necessary but for the moment i can't complete some modules I wanted to do. My code is closed source. I can't promise anything, considering this times, but if I can find time I will write something.

I wanted to program something to manipulate audio signals rather then cv signals but this require DSP knowledge that requires time to be learned. I apologize for the inconvenience.

By the way I'm not dead.
